
export const LexicalTheme = {
    ltr: "ltr",
    rtl: "rtl",
    paragraph: "mb-3 last:mb-0",
    quote: "border-l-4 border-gray-300 pl-4 italic text-gray-700 dark:border-gray-600 dark:text-gray-300 my-4",
    heading: {
        h1: "text-2xl md:text-[28px] font-bold mb-4 mt-6 first:mt-0",
        h2: "text-xl md:text-2xl font-bold mb-3 mt-5 first:mt-0",
        h3: "text-lg md:text-xl font-bold mb-2 mt-4 first:mt-0",
        h4: "text-base md:text-lg font-bold mb-2 mt-3 first:mt-0",
        h5: "text-sm md:text-base font-bold mb-2 mt-2 first:mt-0",
        h6: "text-sm font-bold mb-2 mt-2 first:mt-0",
    },
    list: {
        nested: {
            listitem: "list-none",
        },
        ol: "list-decimal list-outside ml-6 mb-3",
        ul: "list-disc list-outside ml-6 mb-3",
        listitem: "mb-1",
    },
    image: "editor-image",
    hr: "my-4 border-t-2 border-gray-200 dark:border-gray-800",
    link: "text-[#0A57D0] dark:text-blue-400 hover:underline cursor-pointer",
    table: "border-collapse border border-gray-300 dark:border-gray-600 my-4 w-full",
    tableRow: "hover:bg-gray-50 dark:hover:bg-gray-800",
    tableCell: "border border-gray-300 dark:border-gray-600 px-3 py-2 relative align-top min-w-[75px]",
    tableCellHeader: "bg-gray-100 dark:bg-gray-800 font-semibold text-left",
    tableSelection: "bg-blue-100 dark:bg-blue-900/50",
    tableCellSelected: "bg-blue-100 dark:bg-blue-900/50 outline outline-2 outline-blue-500",
    tableAddColumns: "absolute right-0 top-0 h-full w-5 cursor-pointer bg-blue-500/20 hover:bg-blue-500/40",
    tableAddRows: "absolute bottom-0 left-0 w-full h-5 cursor-pointer bg-blue-500/20 hover:bg-blue-500/40",
    text: {
        bold: "font-bold",
        italic: "italic",
        underline: "underline",
        strikethrough: "line-through",
        underlineStrikethrough: "underline line-through",
        code: "bg-gray-100 dark:bg-gray-800 rounded px-1 py-0.5 font-mono text-sm",
        subscript: "sub align-baseline text-xs",
        superscript: "sup align-baseline text-xs",
    },
    code: "bg-gray-100 dark:bg-gray-800 rounded-lg p-4 font-mono text-sm overflow-x-auto my-4 block",
    codeHighlight: {
        atrule: "text-[#07a]",
        attr: "text-[#07a]",
        boolean: "text-[#905]",
        builtin: "text-[#690]",
        cdata: "text-[slategray]",
        char: "text-[#690]",
        class: "text-[#dd4a68]",
        "attr-name": "text-[#690]",
        comment: "text-[slategray]",
        constant: "text-[#905]",
        deleted: "text-[#905]",
        doctype: "text-[slategray]",
        entity: "text-[#9a6e3a]",
        function: "text-[#dd4a68]",
        important: "text-[#e90]",
        inserted: "text-[#690]",
        keyword: "text-[#07a]",
        namespace: "text-[#e90]",
        operator: "text-[#9a6e3a]",
        prolog: "text-[slategray]",
        property: "text-[#905]",
        punctuation: "text-[#999]",
        regex: "text-[#e90]",
        selector: "text-[#690]",
        string: "text-[#690]",
        symbol: "text-[#905]",
        tag: "text-[#905]",
        url: "text-[#9a6e3a]",
        variable: "text-[#e90]",
    },
};
